name: python-lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: Lint YAML examples
        run: |
          yamllint -c "{extends: default, rules: {line-length: {max: 200}}}" examples/
